### ISSUE TITLE
PDM score of transfuser baseline

### ISSUE THREAD

**Issue by RexGPT** [autonomousvision/navsim#35]
Hi @DanielDauner , thank you for your excellent work! I've been running the Transfuser baseline according to the documentation, but I am encountering some discrepancies. Despite multiple runs, my results show the Transfuser baseline consistently fluctuating around 80.0 PDMS, which is lower than the reported 84.0 PDMS in the [NAVSIM paper](https://arxiv.org/pdf/2406.15349) but higher than the 78.0 PDMS reported in the [Hydra-MDP paper](https://arxiv.org/pdf/2406.06978). Could you provide any insights into this variation?

| Method | NC| DAC|TTC| Comf.| EP|PDMS| 
| :---: | :---: | :---: | :---: |  :---: | :---:|:---:|
| Transfuser in NAVSIM paper| 97.7|92.8| 92.8| 100|79.2| 84.0| 
| Transfuser in Hydra-MDP paper| 96.5|87.9| 90.2| 100|73.9| 78.0| 
|Mine reproducement|97.3|89.0|92.1|100|75.4|80.0

**Comment by DanielDauner** [comment]
Hi @RexGPT 

It's unfortunate that you can't reproduce the numbers. May I ask which data split you train on, what batch size you use, and for how many epochs you train?

We trained the TransFuser model on `navtrain` with a batch size of 64 (single GPU) and for 100 epochs. The settings had an impact on the performance. We adapted these parameters as default in NAVSIM v1.1. We also uploaded the checkpoints for TransFuser on [https://huggingface.co/autonomousvision/navsim_baselines](https://huggingface.co/autonomousvision/navsim_baselines).
 
I hope that helps in finding the issue!

Best,
Daniel

**Comment by RexGPT** [comment]
@DanielDauner , Thanks for your prompt reply!
> We trained the TransFuser model on navtrain with a batch size of 64 (single GPU) and for 100 epochs.

Did this mean that you only use a single GPU? I use 8 gpus and train the split on `trainval`, this is my command, which is exactly the same as the doc:

```bash
python $NAVSIM_DEVKIT_ROOT/navsim/planning/script/run_training.py \
        agent=transfuser_agent \
        experiment_name=training_transfuser_agent  \
        train_test_split=navtrain  \
        split=trainval   \
        trainer.params.max_epochs=100 \
        cache_path="${NAVSIM_EXP_ROOT}/training_cache/" \
        use_cache_without_dataset=True  \
        force_cache_computation=False 
```

**Comment by RexGPT** [comment]
Mine batch size is by default, and I use 8 GPUs:
```yaml
dataloader:
  params:
    batch_size: 64  # number of samples per batch
    num_workers: 4  # number of workers for data loading
    pin_memory: true  # pin memory for faster GPU transfer
    prefetch_factor: 2  # number of samples loaded in advance by each worker
```
